### ISSUE TITLE
Rename main branch to haupt

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [marvinborner/DeutschC#2]
To strictly follow the German first principle, the branch should be renamed as well.

Moreover, a proper replacement for `include` should be created.

**Comment by marvinborner** [comment]
I've renamed the branch.
What do you think fits better `inkludieren`, `beifügen`, `einbinden`, ...?

**Comment by TheOneWithTheBraid** [comment]
`einbinden` sounds best (at least not that stolprig as `inkludieren`)

**Comment by marvinborner** [comment]
I'm actually not even sure whether you can create a macro imitating `include`. I've tried some things but they didn't work. If you find a solution I'd be happy to merge it.
